#!/bin/bash
set -euo pipefail

LIST_DIR=/usr/share/seclists

cd "$(dirname "$0")"
mkdir -p ../data


# ssh brute force files
# ---------------------

# usernames
grep -v -e '^pi$' -e '^root$' \
  "${LIST_DIR}/Usernames/top-usernames-shortlist.txt" > ../data/ssh_user

# passwords for root test - part 1
head -n 300 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  > ../data/ssh_root_pass_1

# passwords for root test - part 2
head -n 1000 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ssh_root_pass_1 \
  > ../data/ssh_root_pass_2

# passwords for root test - part 3
head -n 2000 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ssh_root_pass_1 \
  | grep -vxFf ../data/ssh_root_pass_2 \
  > ../data/ssh_root_pass_3

# passwords for user test - part 1
head -n 30 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-1000.txt" \
  > ../data/ssh_user_pass_1

# passwords for user test - part 2
head -n 100 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-1000.txt" \
  | grep -vxFf ../data/ssh_user_pass_1 \
  > ../data/ssh_user_pass_2

# passwords for user test - part 3
head -n 200 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-1000.txt" \
  | grep -vxFf ../data/ssh_user_pass_1 \
  | grep -vxFf ../data/ssh_user_pass_2 \
  > ../data/ssh_user_pass_3


# ftp brute force files
# ---------------------

# usernames
grep -v -e '^pi$' \
  "${LIST_DIR}/Usernames/top-usernames-shortlist.txt" > ../data/ftp_user

# passwords - part 1
head -n 500 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  > ../data/ftp_pass_1

# passwords - part 2
head -n 1500 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ftp_pass_1 \
  > ../data/ftp_pass_2

# passwords - part 3
head -n 4000 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ftp_pass_1 \
  | grep -vxFf ../data/ftp_pass_2 \
  > ../data/ftp_pass_3


# http
# ----

# user-agents
l=https://raw.githubusercontent.com/Kikobeats/top-user-agents/master/index.json
curl -s ${l} | grep M | cut -d'"' -f2 > ../data/http_user-agent

# common www files and dirs - fast
d=/usr/share/seclists/Discovery/Web-Content
cat ${d}/raft-small-files.txt \
  ${d}/raft-small-directories.txt \
  ${d}/api/api-endpoints.txt \
  ${d}/URLs/*.txt \
  | sed 's|^/||' \
  | sed '/^\//d' \
  | sed 's|/$||' \
  | sed '/\/$/d' \
  | sed '/ /d' \
  | sed '/\?/d' \
  | sed '/\*/d' \
  | sed '/\!/d' \
  | sed '/\&/d' \
  | sed '/\$/d' \
  | sed '/\t/d' \
  | sed '/#/d' \
  | sed '/</d' \
  | sed '/^%/d' \
  | sed '/^$/d' \
  | sort -u \
  > ../data/http_common_fast

# common www files and dirs - full
cat ${d}/raft-large-files.txt \
  ${d}/raft-large-directories.txt \
  ${d}/CMS/* \
  ${d}/SVNDigger/all.txt \
  ${d}/api/*.txt \
  ${d}/{A,C,F,H,I,J,O,R,S,U,V,a,f,g,h,j,n,o,p,q,u,v}*.txt \
  ${d}/Logins.fuzz.txt \
  ${d}/LotusNotes.fuzz.txt \
  ${d}/Passwords.fuzz.txt \
  ${d}/PHP.fuzz.txt \
  ${d}/coldfusion.txt \
  ${d}/confluence-administration.txt \
  ${d}/domino-dirs-coldfusion39.txt \
  ${d}/domino-endpoints-coldfusion39.txt \
  ${d}/reverse-proxy-inconsistencies.txt \
  ${d}/ror.txt \
  ${d}/sap.txt \
  ${d}/swagger.txt \
  ${d}/tomcat.txt \
  ${d}/weblogic.txt \
  ${d}/websphere.txt \
  | sed 's|^/||' \
  | sed '/^\//d' \
  | sed 's|/$||' \
  | sed '/\/$/d' \
  | sed '/ /d' \
  | sed '/\?/d' \
  | sed '/\*/d' \
  | sed '/\!/d' \
  | sed '/\&/d' \
  | sed '/\$/d' \
  | sed '/\t/d' \
  | sed '/#/d' \
  | sed '/</d' \
  | sed '/^%/d' \
  | sed '/^$/d' \
  | sed '/svn\/pristine/d' \
  | sort -u \
  > ../data/http_common_full

# common www dirs
cat ${d}/raft-large-directories.txt \
  | sed '/ /d' \
  | sed '/^$/d' \
  > ../data/http_dir

# files for recursive scan
cat ../data/http_common_fast \
  | grep -v '/' \
  | grep -v '^\.$' \
  | grep -v '^\.\.$' \
  > ../data/http_file_rec_fast

# files for recursive scan
cat ../data/http_common_full \
  | grep -v '/' \
  | grep -v '^\.$' \
  | grep -v '^\.\.$' \
  > ../data/http_file_rec_full

echo done.
