#!/bin/bash
set -euo pipefail

LIST_DIR=/usr/share/seclists

cd "$(dirname "$0")"
mkdir -p ../data


# ssh brute force files
# ---------------------

# usernames
grep -v -e '^pi$' -e '^root$' \
  "${LIST_DIR}/Usernames/top-usernames-shortlist.txt" > ../data/ssh_user

# passwords for root test - part 1
head -n 300 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  > ../data/ssh_root_pass_1

# passwords for root test - part 2
head -n 1000 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ssh_root_pass_1 \
  > ../data/ssh_root_pass_2

# passwords for root test - part 3
head -n 2000 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ssh_root_pass_1 \
  | grep -vxFf ../data/ssh_root_pass_2 \
  > ../data/ssh_root_pass_3

# passwords for user test - part 1
head -n 30 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-1000.txt" \
  > ../data/ssh_user_pass_1

# passwords for user test - part 2
head -n 100 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-1000.txt" \
  | grep -vxFf ../data/ssh_user_pass_1 \
  > ../data/ssh_user_pass_2

# passwords for user test - part 3
head -n 200 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-1000.txt" \
  | grep -vxFf ../data/ssh_user_pass_1 \
  | grep -vxFf ../data/ssh_user_pass_2 \
  > ../data/ssh_user_pass_3


# ftp brute force files
# ---------------------

# usernames
grep -v -e '^pi$' \
  "${LIST_DIR}/Usernames/top-usernames-shortlist.txt" > ../data/ftp_user

# passwords - part 1
head -n 500 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  > ../data/ftp_pass_1

# passwords - part 2
head -n 1500 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ftp_pass_1 \
  > ../data/ftp_pass_2

# passwords - part 3
head -n 4000 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  | grep -vxFf ../data/ftp_pass_1 \
  | grep -vxFf ../data/ftp_pass_2 \
  > ../data/ftp_pass_3


# http
# ----

# user-agents
l=https://raw.githubusercontent.com/Kikobeats/top-user-agents/master/index.json
curl -s ${l} | grep M | cut -d'"' -f2 > ../data/http_user-agent

# common www files and dirs
d=/usr/share/seclists/Discovery/Web-Content
cat ${d}/raft-small-files.txt \
  ${d}/common.txt \
  ${d}/Common-DB-Backups.txt \
  ${d}/Logins.fuzz.txt \
  ${d}/PHP.fuzz.txt \
  ${d}/Passwords.fuzz.txt \
  ${d}/common-api-endpoints-mazen160.txt \
  ${d}/nginx.txt \
  ${d}/proxy-conf.fuzz.txt \
  | sed 's|^/||' \
  | sed '/^\//d' \
  | sed 's|/$||' \
  | sed '/\/$/d' \
  | sed '/ /d' \
  | sed '/\?/d' \
  | sed '/\*/d' \
  | sed '/\!/d' \
  | sed '/\&/d' \
  | sed '/\$/d' \
  | sed '/\t/d' \
  | sed '/#/d' \
  | sed '/:/d' \
  | sed '/</d' \
  | sed '/^%/d' \
  | sed '/^$/d' \
  | sort -u \
  > ../data/http_url_enum

# common www dirs
cat ${d}/raft-large-directories.txt \
  | sed '/ /d' \
  | sed '/^$/d' \
  > ../data/http_dir

# files for recursive scan
cat ../data/http_url_enum \
  | grep -v '/' \
  | grep -v '^\.$' \
  | grep -v '^\.\.$' \
  > ../data/http_url_enum_rec_file

# users for web login testing
cat << EOF > ../data/weblogin_user
a adm admin administrator anonymous default ftp ftpuser guest httpadmin info
localadmin none root supervisor test uploader user user1 webserver
EOF
sed -i 's| |\n|g' ../data/weblogin_user

# passwords for web login testing
head -n 2000 "${LIST_DIR}/Passwords/xato-net-10-million-passwords-10000.txt" \
  > ../data/weblogin_pass

# test data for fuff fuzzing
> ../data/ffuf_testlist
for i in $(seq 0 15); do
  printf "x%x\n" $i >> ../data/ffuf_testlist
done


# common locations of files on Windows
# ------------------------------------

cp /usr/share/seclists/Fuzzing/LFI/LFI-gracefulsecurity-windows.txt \
  ../data/files_win


# nmap port split is not used currently by sectest, keeping it just in case

# nmap port lists
# ---------------

# nmap port split is not used currently by sectest, keeping it just in case

sort -r -k3 /usr/share/nmap/nmap-services \
  | grep -v '^#' \
  | grep '/tcp	' \
  | head -n10000 \
  | sed 's|\t0\..*|\t0.000000|' \
  > ../data/nmap_servicedb_tcp_init_1

# add missing ports from 1-10000 range

cut -f2 ../data/nmap_servicedb_tcp_init_1 \
  > ../data/nmap_servicedb_tcp_init_1_tmp

seq -f '%f/tcp' 1 10000 \
  | sed 's|\.000000||' \
  > ../data/nmap_servicedb_tcp_init_1_add

grep -vxFf ../data/nmap_servicedb_tcp_init_1_tmp \
  ../data/nmap_servicedb_tcp_init_1_add \
    | sed 's|^|custom	|' \
    | sed 's|$|	0.000000|' \
    >> ../data/nmap_servicedb_tcp_init_1

# prepare ports for the second tcp init run

cut -f2 ../data/nmap_servicedb_tcp_init_1 \
  > ../data/nmap_servicedb_tcp_init_1_tmp

seq -f '%f/tcp' 1 65535 \
  | sed 's|\.000000||' \
  > ../data/nmap_servicedb_tcp_init_2_tmp

grep -vxFf ../data/nmap_servicedb_tcp_init_1_tmp \
  ../data/nmap_servicedb_tcp_init_2_tmp \
    | sed 's|^|custom	|' \
    | sed 's|$|	0.000000|' \
    > ../data/nmap_servicedb_tcp_init_2

rm ../data/nmap_servicedb_tcp_init_*_{tmp,add}

# prepare ports for the first udp init run

sort -r -k3 /usr/share/nmap/nmap-services \
  | grep -v '^#' \
  | grep '/udp	' \
  | head -n1000 \
  | sed 's|\t0\..*|\t0.000000|' \
  > ../data/nmap_servicedb_udp_init_1 || :

# prepare ports for the second udp init run

sort -r -k3 /usr/share/nmap/nmap-services \
  | grep -v '^#' \
  | grep '/udp	' \
  | head -n11000 \
  | sed 's|\t0\..*|\t0.000000|' \
  > ../data/nmap_servicedb_udp_init_2_tmp || :

grep -vxFf ../data/nmap_servicedb_udp_init_1 \
  ../data/nmap_servicedb_udp_init_2_tmp \
    > ../data/nmap_servicedb_udp_init_2

rm ../data/nmap_servicedb_udp_init_*_tmp

echo done.

